ci: build zephyr samples on PR
This commit adds initial support for automated builds on PR for
zephyr-based projects.

Signed-off-by: Paul Buckley <paul@hubble.com>

diff --git a/.github/workflows/compliance.yaml b/.github/workflows/compliance.yaml
--- a/.github/workflows/compliance.yaml
+++ b/.github/workflows/compliance.yaml
@@ -3,10 +3,10 @@ name: Compliance Checks
 on:
   pull_request:
     types:
-    - edited
-    - opened
-    - reopened
-    - synchronize
+      - edited
+      - opened
+      - reopened
+      - synchronize
 
 jobs:
   check_compliance:
@@ -14,51 +14,51 @@ jobs:
     name: Run compliance checks on patch series (PR)
 
     steps:
-    - name: Checkout the code
-      uses: actions/checkout@v4
-      with:
-        ref: ${{ github.event.pull_request.head.sha }}
-        fetch-depth: 0
+      - name: Checkout the code
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
+          fetch-depth: 0
 
-    - name: Set up Python
-      uses: actions/setup-python@v5
-      with:
-        python-version: 3.11
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: 3.11
 
-    - name: cache-pip
-      uses: actions/cache@v4
-      with:
-        path: ~/.cache/pip
-        key: ${{ runner.os }}-pip-${{ hashFiles('.github/workflows/compliance.yml') }}
+      - name: cache-pip
+        uses: actions/cache@v4
+        with:
+          path: ~/.cache/pip
+          key: ${{ runner.os }}-pip-${{ hashFiles('.github/workflows/compliance.yml') }}
 
-    - name: Install dependencies
-      run: |
-    #    pip install clang-format
-        pip install gitlint
+      - name: Install dependencies
+        run: |
+          pip install gitlint
+          #    pip install clang-format
 
-    # Temporarily disable clang-format checks until a standardized configuration
-    # is established.
-    # Currently, there are formatting inconsistencies that result in
-    # improper code styling. Example of such issues:
-    #
-    # static int my_var[] = {
-    #      1, 2, 3, 4
-    #};
-    #
-    # - name: Run clang-format
-    #   shell: bash
-    #   run: |
-    #     git clang-format --verbose --extensions c,h --diff --diffstat origin/$GITHUB_BASE_REF
+          # Temporarily disable clang-format checks until a standardized configuration
+          # is established.
+          # Currently, there are formatting inconsistencies that result in
+          # improper code styling. Example of such issues:
+          #
+          # static int my_var[] = {
+          #      1, 2, 3, 4
+          # };
+          #
+          # - name: Run clang-format
+          #   shell: bash
+          #   run: |
+          #     git clang-format --verbose --extensions c,h --diff --diffstat origin/$GITHUB_BASE_REF
 
-    - name: Run gitlint
-      run: |
-        git config --global --add safe.directory $GITHUB_WORKSPACE
-        gitlint --commits origin/$GITHUB_BASE_REF..
+      - name: Run gitlint
+        run: |
+          git config --global --add safe.directory $GITHUB_WORKSPACE
+          gitlint --commits origin/$GITHUB_BASE_REF..
 
-    - name: Check for PR description
-      if: ${{ github.event.pull_request.body == '' }}
-      continue-on-error: true
-      id: pr_description
-      run: |
-        echo "Pull request description cannot be empty."
-        exit 1
+      - name: Check for PR description
+        if: ${{ github.event.pull_request.body == '' }}
+        continue-on-error: true
+        id: pr_description
+        run: |
+          echo "Pull request description cannot be empty."
+          exit 1
